apiVersion: v1
kind: Pod
metadata:
  name: voting-result-app
  labels:
    name: demo-voting-app
spec:
  containers:
    - name: voting-result-app
      image: eesprit/voting-app-result
      ports:
        - containerPort: 80
