apiVersion: v1
kind: Service
metadata:
  name: voting-result-pod
  labels:
    name: result-service
    app: demo-voting-app
spec:
  type: NodePort
  selector:
    name: voting-result-pod
    app: demo-voting-app
  ports:
    - port: 80
      targetPort: 80
