apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
  template:
    metadata:
      labels:
        app: demo-voting-app
    spec:
      containers:
        - name: demo-voting-app
          image: eesprit/voting-app-vote:error
          ports:
            - containerPort: 80
