apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-result-deployment
  labels:
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app
      name: voting-result-pod
  template:
    metadata:
      labels:
        app: demo-voting-app
        name: voting-result-pod
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
