apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: voting-app-replicaset
spec:
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: demo-voting-app
    spec:
      containers:
        - name: voting-app-pod
          image: eesprit/voting-app-vote
          ports:
            - containerPort: 80
  replicas: 4
  selector:
    matchLabels:
      app: demo-voting-app
